### ISSUE TITLE
Tests break on local platform after the weekend. Trying to download non-existant v34.0

### ISSUE THREAD

**Issue by apple-corps** [webdriverio-community/node-geckodriver#325]
Hi folks, my tests were running locally against my platform this past Friday. But now on Tuesday they are no longer executing. 

```
Error: Error: Failed to download binary (statusCode 404): Not Found
    at download (file:////test-root//node_modules/geckodriver/src/install.ts:58:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Launcher.run (file:////test-root//node_modules/@wdio/cli/build/launcher.js:102:13)
    at async Module.run (file:////test-root//node_modules/@wdio/cli/build/run.js:64:20)
Error: Failed to download binary (statusCode 404): Not Found
    at download (file:////test-root//node_modules/geckodriver/src/install.ts:58:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Launcher.run (file:////test-root//node_modules/@wdio/cli/build/launcher.js:102:13)
    at async Module.run (file:////test-root//node_modules/@wdio/cli/build/run.js:64:20)
```

```
2024-01-03T05:01:22.930Z INFO @wdio/cli:launcher: Run onPrepare hook
2024-01-03T05:01:22.931Z INFO @wdio/utils: Setting up browser driver for: firefox@stable
2024-01-03T05:01:22.931Z INFO @wdio/utils: Setting up browser binaries for: firefox@stable
2024-01-03T05:01:25.369Z INFO geckodriver: Detected Geckodriver v0.34.0 to be latest
2024-01-03T05:01:25.370Z INFO geckodriver: Downloading Geckodriver from https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux-aarch64.tar.gz
2024-01-03T05:01:25.576Z INFO @wdio/local-runner: Shutting down spawned worker
2024-01-03T05:01:25.827Z INFO @wdio/local-runner: Waiting for 0 to shut down gracefully
```

Last release of geckodriver is 33.0 : https://github.com/mozilla/geckodriver/releases

**Comment by apple-corps** [comment]
Setting this in my capabilities and downloading geckodriver 33 as a suggested workaround.
      
      'wdio:geckodriverOptions': {
        binary: "my_home/Downloads/geckodriver",
      },
      'moz:firefoxOptions': {
       binary: '/usr/bin/firefox'
      },

**Comment by christian-bromann** [comment]
Asked in the Selenium chat and got a very helpful response from Boni:

```
Selenium Manager uses this JSON file we maintain for that: https://raw.githubusercontent.com/SeleniumHQ/selenium/trunk/common/geckodriver/geckodriver-support.json

It is based on the official doc: https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html

But since the official mapping is on the way, we decided to maintain ours: https://bugzilla.mozilla.org/show_bug.cgi?id=1794550

Alternative, you can request the following URL:
https://github.com/mozilla/geckodriver/releases/latest

Which will redirect you to the latest tag
```

Any contribution fixing this bug would be appreciated.

**Comment by christian-bromann** [comment]
Seems like it is now available to download: https://twitter.com/FirefoxDevTools/status/1742510381690405229 so the issue is resolved. However it would be great if we can get the latest version from another source so that this doesn't happen anymore.
